---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - polyscope.my.domain
  resources:
  - scopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - polyscope.my.domain
  resources:
  - scopes/finalizers
  verbs:
  - update
- apiGroups:
  - polyscope.my.domain
  resources:
  - scopes/status
  verbs:
  - get
  - patch
  - update
