# This rule is not used by the project polyscope itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to polyscope.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: polyscope
    app.kubernetes.io/managed-by: kustomize
  name: scope-viewer-role
rules:
- apiGroups:
  - polyscope.my.domain
  resources:
  - scopes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - polyscope.my.domain
  resources:
  - scopes/status
  verbs:
  - get
