apiVersion: polyscope.my.domain/v1alpha1
kind: Scope
metadata:
  labels:
    app.kubernetes.io/name: polyscope
    app.kubernetes.io/managed-by: kustomize
  name: scope-sample
spec:
  # TODO(user): Add fields here
